######################################################################
# Automatically generated by qmake (2.01a) Fri May 20 15:40:58 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += addcontact.h chat.h include.hpp login.h
SOURCES += addcontact.cpp chat.cpp login.cpp main.cpp
